#!/usr/bin/env bash
# Displays PID and name of processes whose name contains the word bash
for pid in /proc/[0-9]*/
do
    pid=${pid//[^0-9]/}
    name=$(cat /proc/$pid/comm 2>/dev/null)
    if echo "$name" | grep -q "bash"
    then
        echo "$pid $name"
    fi
done

